// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqVqYisVTkgSNq0VV-awn9MK3c4Z7LjWM',
    appId: '1:957388472374:web:b99bf4ddc2a0883386d897',
    messagingSenderId: '957388472374',
    projectId: 'donobox-9e4c6',
    authDomain: 'donobox-9e4c6.firebaseapp.com',
    storageBucket: 'donobox-9e4c6.appspot.com',
    measurementId: 'G-SGTFL0KJ5E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD09TEGEvsK9_mzTM-C7enaW5X8j45ZQTc',
    appId: '1:957388472374:android:08bbc001e621623586d897',
    messagingSenderId: '957388472374',
    projectId: 'donobox-9e4c6',
    storageBucket: 'donobox-9e4c6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdto3eCYdpJZz77DUJDYptWV6dyzkx_-k',
    appId: '1:957388472374:ios:64f1f67bf2483e7b86d897',
    messagingSenderId: '957388472374',
    projectId: 'donobox-9e4c6',
    storageBucket: 'donobox-9e4c6.appspot.com',
    iosBundleId: 'com.example.Donobox',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdto3eCYdpJZz77DUJDYptWV6dyzkx_-k',
    appId: '1:957388472374:ios:3c345890e8f852a386d897',
    messagingSenderId: '957388472374',
    projectId: 'donobox-9e4c6',
    storageBucket: 'donobox-9e4c6.appspot.com',
    iosBundleId: 'com.example.Donobox.RunnerTests',
  );
}
