// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAm8Xd55SPcfrauh8ggdOIwxk5xGEjCG1U',
    appId: '1:1012299080197:web:7980e522586a4d8dc2326c',
    messagingSenderId: '1012299080197',
    projectId: 'donobox-2024',
    authDomain: 'donobox-2024.firebaseapp.com',
    storageBucket: 'donobox-2024.appspot.com',
    measurementId: 'G-NT63JYTD04',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAk4iUauf67tenilUlQns0dtpoFQQHKnPg',
    appId: '1:1012299080197:android:c6b052e041ab71bcc2326c',
    messagingSenderId: '1012299080197',
    projectId: 'donobox-2024',
    storageBucket: 'donobox-2024.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFfWtATuRJ3daaJ-eH0bVAx51djQ2zxZo',
    appId: '1:1012299080197:ios:a9193e1d6d57e2d6c2326c',
    messagingSenderId: '1012299080197',
    projectId: 'donobox-2024',
    storageBucket: 'donobox-2024.appspot.com',
    iosBundleId: 'com.example.Donobox',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFfWtATuRJ3daaJ-eH0bVAx51djQ2zxZo',
    appId: '1:1012299080197:ios:3cf4cafa7e670ffbc2326c',
    messagingSenderId: '1012299080197',
    projectId: 'donobox-2024',
    storageBucket: 'donobox-2024.appspot.com',
    iosBundleId: 'com.example.Donobox.RunnerTests',
  );
}
